Add `anchor-scope` support
oddbird/css-anchor-positioning pull request #217
Opened 2024-07-20 05:09 UTC by mmalerba

![](https://source.unsplash.com/featured/?cute,animal&CHANGE_ME)

## Related Issue(s)
_Reminder to add related issue(s), if available._

## Steps to test/reproduce
_Please explain how to best reproduce the issue and/or test the changes locally (including the pages/URLs/views/states to review)._

## Show me
_Provide screenshots/animated gifs/videos if necessary._

2024-07-22 20:16 UTC, jgerigmeyer requested changes
@mmalerba This is great -- thanks! 🚀 A few tasks before it's ready to merge:

- [ ] There are some tests in `validate.test.ts` that are using the outdated call signature for `validatedForPositioning` and `isAcceptableAnchorElement`.
- [ ] We merged in #213 this morning, and there are a few merge conflicts -- could you rebase off of `main`?

2024-07-22 21:37 UTC, mmalerba commented on src/parse.ts
> +    value == AnchorScopeValue.None
Fixed the tests, rebased, and pushed. I actually removed this validation when I was rebasing, because I noticed that `anchor-name` wasn't really doing it anyways, and I think it would make more sense to just strip invalid declarations in the pre-processing (cascade) step. Then we can just assume things are valid in the later phases

2024-07-23 14:28 UTC, jgerigmeyer approved these changes
👍 

I think you could remove `anchor-scope` from the "Limitations" list in the README, or add a clarification that it's not supported for pseudo-elements.

2024-07-23 14:28 UTC, jgerigmeyer commented on src/parse.ts
```suggestion
```

2024-07-23 14:28 UTC, jgerigmeyer commented on src/validate.ts
> +  // TODO: handle anchor-scope for pseudo-elements.
If we're not planning to handle this in this PR, could you file a new issue for it?

2024-07-23 18:59 UTC, merged